# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js '12.x'
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build the docker-compose stack
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps -a

      - name: Install dependencies
        run: yarn
                
      - name: Run Migrations
        run: yarn typeorm migration:run

      - name: Run tests
        run: yarn test

        env:
          SECRET_KEY: "9903f1bb0f4bbe259a609d0ae4da576a"
          DATABASE_URL: "postgres://postgres:docker@localhost:5432/EnglishTalkingApi"
